openapi: 3.0.4
info:
  title: Trivia Generator
  description: Trivia is a simple tool for getting trivia questions. It returns a random trivia question based on your selected category.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/trivia:
    get:
      summary: Get Random Trivia Question
      description: Trivia is a simple tool for getting trivia questions. It returns a random trivia question based on your selected category.
      operationId: trivia
      parameters:
      - name: category
        default: general
        in: query
        schema:
          type: string
        required: false
        description: The category of the trivia question (e.g., general, entertainment, history, etc)
        example: general
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  question: What kind of person is described by the expression green around the gills?
                  answer: Physically ill
                  options:
                  - A Physically ill
                  - B New at fishing
                  - C Gardner novice
                  - D Jealous over someone
                  category: general
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
