openapi: 3.0.4
info:
  title: Trivia Generator
  description: >-
    Trivia is a simple tool for getting trivia questions. It returns a random
    trivia question based on your selected category.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/trivia:
    get:
      summary: Get Random Trivia Question
      description: Get a random trivia question
      operationId: trivia
      parameters:
        - name: category
          in: query
          schema:
            type: string
          required: false
          description: The category of the trivia question
          example: general
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  question: >-
                    Is the Pink Cadillac the trademark of Mary Kay beauty
                    products?
                  answer: 'Yes'
                  options:
                    - A Yes
                    - B No
                  category: general
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
